# Generated by Django 3.1.4 on 2021-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(default=1, upload_to='PDF'),
            preserve_default=False,
        ),
    ]
