# Generated by Django 3.1.4 on 2021-03-28 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'message', 'pdf')},
        ),
    ]
