# Generated by Django 3.1.4 on 2021-03-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210329_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='subject',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
