# Generated by Django 3.1.4 on 2021-03-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210329_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('subject', models.TextField(blank=True, max_length=250)),
                ('document', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
