# Generated by Django 3.1.4 on 2021-03-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210329_0151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='UploadFile',
        ),
    ]
